services:
  database:
    image: postgres:15.4
    container_name: database
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - main
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - main
    restart: always
    ports:
      - 5050:80

networks:
  main:
    external: true

volumes:
  database:
    driver: local
    driver_opts:
      device: ./database
      type: volume
      o: bind
